Do task 1
LudvigHz/TDT4165-scala-project pull request #2
Opened 2020-10-27 09:20 UTC by erlingfn

Add a solution to task 1. Don't really know scala yet, so there is surely a lot of room for improvement.

2020-10-30 14:19 UTC, LudvigHz requested changes

2020-10-30 14:19 UTC, LudvigHz commented on tasks/task1.scala
> +  def sumRecursion(values: List[Int], partialSum: Int): Int = {
Have `partialSum` with a default, so that we can call `sumRecursion` with only the list as an argument?
`partialSum: Int = 0`

2020-10-30 14:19 UTC, LudvigHz commented on tasks/task1.scala
> +  val generateValues = (1 to 50).toList
Is this **for**?

2020-10-30 14:19 UTC, LudvigHz commented on tasks/task1.scala
> +        fibTailRec(N - 1, accumulator * N)
Is this fibonacci?

2020-10-30 16:08 UTC, erlingfn commented on tasks/task1.scala
> +<<<<<<< HEAD
:upside_down_face:

2020-11-05 19:28 UTC, LudvigHz approved these changes

2020-11-05 19:28 UTC, merged